server {
    listen 80;
    
    root /usr/share/nginx/html/browser; # Ajusta según la carpeta dist de tu Angular
    index index.html;

    # 1. Servir la aplicación Angular (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Conectar Angular con Laravel internamente
    # Cuando Angular llame a /api/..., Nginx lo manda al contenedor 'backend'
    location /api {
        proxy_pass http://backend:80; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}